---
- hosts: djangocms-web
  vars_files:
    - rds-creds.yml
  tasks: 
  - name: install system packages
    apt: name={{item}} update_cache=yes
    with_items:
      - libpq-dev 
      - postgresql-client-9.4 
      - python-dev 
      - python-pip 
      - git 
      - nginx
  - name: create django group
    group: name=django state=present
  - name: create django user
    user: name=django groups=django,www-data
  - name: clone django-cms repo
    git: repo=https://github.com/purbohadi/DjangoCMS.git dest=/srv/DjangoCMSDemo force=yes
  - name: pip install requirements
    pip: requirements=/srv/DjangoCMSDemo/requirements.txt
  - name: change ownership of application
    file: path=/srv/DjangoCMSDemo owner=root group=root recurse=yes 
  - name: add nginx site config
    copy: src=files/django-cms-site dest=/etc/nginx/sites-available/django-cms
  - name: enable django-cms site 
    file: src=/etc/nginx/sites-available/django-cms dest=/etc/nginx/sites-enabled/django-cms state=link
  - name: delete default nginx site
    file: path=/etc/nginx/sites-enabled/default state=absent
  - name: add gunicorn systemd service
    template: src=files/gunicorn.service dest=/etc/systemd/system/gunicorn.service mode=0755
  - name: add gunicorn systemd socket
    copy: src=files/gunicorn.socket dest=/etc/systemd/system/gunicorn.socket mode=0755
  - name: set gunicorn rundir permissions
    file: path=/run/gunicorn state=directory owner=django group=www-data mode=0775 recurse=yes
  - name: reload systemd
    command: /bin/systemctl --system daemon-reload
  - name: enable gunicorn service
    service: name=gunicorn enabled=yes
  - name: bounce gunicorn
    service: name=gunicorn state=restarted
  - name: bounce nginx
    service: name=nginx state=restarted
